### ISSUE TITLE
close method for RemoteMongoClient

### ISSUE THREAD

**Issue by caduandrade** [mongodb/stitch-android-sdk#103]
Hi!

I don't want use RemoteMongoCollection.sync(). I would like keep my local and remote databases separated and sync manually.

After get a RemoteMongoClient, I can't close it and open the local database. There is no method to close as MongoClient.close(). 

I get exception: _com.mongodb.embedded.client.MongoClientEmbeddedException: Could not create a new embedded cluster. Ensure existing MongoClients are fully closed before trying to create a new one._

```
StitchAppClient stitchAppClient = Stitch.initializeDefaultAppClient("...");

RemoteMongoClient remoteMongoClient = stitchAppClient.getServiceClient(RemoteMongoClient.factory, "...");
// fetch data here...
remoteMongoClient.close(); // I need this

MongoClient mongoClient = stitchAppClient.getServiceClient(LocalMongoDbService.clientFactory);

```

**Comment by adamchel** [comment]
Hi @caduandrade thanks for opening this issue,

At this stage in the mobile sync beta, we unfortunately do not support having a non-synced local client and remote client in the same application. This is due to a technical limitation in the underlying embedded MongoDB.

We are however planning on working on a feature that may help your case. We can't share more details but I will keep you updated in the coming weeks.

Let us know if you have any further questions, and please open another issue if you run into any other problems.
