### ISSUE TITLE
Why the version starts from 21

### ISSUE THREAD

**Issue by eslam2010011** [mongodb/stitch-android-sdk#125]
Why the version starts from 21

**Comment by adamchel** [comment]
Hi @eslam2010011 

I assume you are referring to the minimum Android API level to build applications with Stitch. We made it API Level 21 (which is Android 5.0 Lollipop) because it supports 90% of Android devices, and the SDK uses features that require that to be the minimum version.

Let us know if you have any further questions. Otherwise I will close this ticket. Feel free to also open another ticket if you have another issue.
